displayName=Boss Tracker
author=camjewell
description=Tracks kills per hour, session stats, boss goals, loot and historical stats across OSRS bosses
tags=pvm,boss,kph,kills per hour,bossing,kill times,loot,goals
version=1.0
plugins=com.camjewell.bosstracker.BossTrackerPlugin
build=standard
